# Generated by Django 5.0.4 on 2026-04-30 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='folder', help_text="Lucide icon name (e.g. 'folder', 'book', 'code')", max_length=50)),
                ('colour', models.CharField(blank=True, default='#6366f1', help_text='Hex colour code', max_length=7)),
                ('is_smart', models.BooleanField(default=False, help_text='If True, cards are auto-populated based on smart_filter')),
                ('smart_filter', models.JSONField(blank=True, default=dict, help_text="Saved filter config: {type: 'youtube', is_favourite: true, ...}")),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first in sidebar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['user', 'sort_order'], name='collections_user_id_d4a096_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
