# Generated by Django 5.0.4 on 2026-04-30 10:08

import django.db.models.deletion
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UUIDTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('link', 'Link'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('note', 'Note'), ('image', 'Image'), ('pdf', 'PDF'), ('voice', 'Voice Note'), ('code', 'Code Snippet'), ('reel', 'Reel / Short'), ('chat', 'Chat Excerpt'), ('file', 'File')], default='link', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('body', models.TextField(blank=True, help_text='Markdown content for notes, code snippets, chat excerpts')),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('file', models.FileField(blank=True, help_text='Uploaded file (image, PDF, audio, etc.)', null=True, upload_to='cards/files/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated thumbnail', null=True, upload_to='cards/thumbnails/%Y/%m/')),
                ('favicon_url', models.URLField(blank=True, max_length=500)),
                ('og_image_url', models.URLField(blank=True, max_length=2000)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Type-specific data: channel, stars, duration, language, etc.')),
                ('transcript', models.TextField(blank=True, help_text='Speech-to-text output for voice notes')),
                ('is_favourite', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='collections.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cards.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'type'], name='cards_card_user_id_ca8247_idx'), models.Index(fields=['user', 'is_favourite'], name='cards_card_user_id_a5ee29_idx'), models.Index(fields=['user', 'is_archived'], name='cards_card_user_id_b50aff_idx'), models.Index(fields=['user', 'collection'], name='cards_card_user_id_f306c6_idx'), models.Index(fields=['created_at'], name='cards_card_created_591b38_idx'), models.Index(fields=['reminder_at'], name='cards_card_reminde_097278_idx'), models.Index(fields=['user', 'is_archived', '-created_at'], name='cards_card_user_id_ee9452_idx')],
            },
        ),
    ]
